"""LLM SQL Assistant — heuristic vs LLM comparison page.

This page demonstrates the value the LLM adds over the offline heuristic
fast path (``src.heuristic_nl``).  It runs the *same* natural-language
input through both paths and shows the user the two resulting
:class:`~src.query_model.QueryModel` plans side by side.

Safety: nothing on this page executes SQL.  Both paths produce a
``QueryModel``; the SQL is generated by ``QueryModel.to_sql()`` and shown
to the user for inspection only.  The user clicks "Use this plan" to
hand the chosen plan off to the Studio page, where the existing
``▶ Run query`` button runs it through the same executor blocklist as
every other query in the app.

Architecture
------------
- The heuristic path is local, free, and runs eagerly on every input.
- The LLM path uses the production ``nl_to_query_model`` entry point,
  with the same ``LLMConfig`` (provider, model, host) the Studio page is
  using — the ``⚙ LLM`` popover in the header controls both pages.
- The "Use this plan" button writes the chosen ``QueryModel`` into
  ``st.session_state.model`` / ``st.session_state.last_sql`` and calls
  ``st.switch_page`` back to the Studio, where the SQL preview is
  already populated.
"""

from __future__ import annotations

import copy
import time
from dataclasses import dataclass
from typing import List, Optional, Tuple

import streamlit as st

from src.config import load_config
from src.heuristic_nl import HeuristicResult, parse_heuristic
from src.llm.natural_language import (
    LLMConfig,
    LLMError,
    RouteToPythonError,
    load_llm_config,
    make_llm_client,
    nl_to_query_model,
)
from src.query_model import QueryModel
from src.streamlit_app import state
from src.streamlit_app.demo_dataset import (
    DEMO_DESCRIPTION,
    DEMO_NAME,
    load_demo,
)
from src.streamlit_app.styles import inject_css


# ---------------------------------------------------------------------------
# Example questions — used as clickable chips and to seed the input
# ---------------------------------------------------------------------------

_EXAMPLE_QUESTIONS: List[str] = [
    "monthly revenue trend 2024",
    "top 10 customers by margin",
    "count orders by status",
    "compare EMEA vs AMER year-over-year",
    "average unit price by category",
    "revenue in 2024 by region",
]


# ---------------------------------------------------------------------------
# Safety banner
# ---------------------------------------------------------------------------

_SAFETY_PILLARS: List[Tuple[str, str]] = [
    ("🔒", "Read-only SQLite connection (PRAGMA query_only)"),
    ("📋", "LLM produces a JSON plan, never SQL"),
    ("✅", "Schema validation of every column name"),
    ("🎯", "Operator & aggregation function allowlists"),
    ("🟧", "SELECT-only: to_sql() cannot emit INSERT/UPDATE/DELETE/DROP"),
    ("🛡", "Executor blocklist as a final guardrail"),
]


def _render_safety_banner() -> None:
    pills = "".join(
        f'<span class="safety-pillar" title="{title}">'
        f'<span class="pillar-icon">{icon}</span>'
        f'<span class="pillar-text">{title}</span>'
        f"</span>"
        for icon, title in _SAFETY_PILLARS
    )
    st.markdown(
        '<div class="llm-assistant-safety">'
        '<div class="safety-heading">How the LLM stays safe here</div>'
        f"{pills}"
        "</div>",
        unsafe_allow_html=True,
    )


# ---------------------------------------------------------------------------
# Schema loading
# ---------------------------------------------------------------------------


def _ensure_schema_loaded() -> bool:
    """Make sure ``st.session_state.schema`` is populated.

    Reuses whatever the Studio page already loaded if present.  Otherwise
    loads the bundled demo dataset (same path the Studio uses) so the
    showcase works on a clean visit.
    """
    if st.session_state.get("schema"):
        return True

    try:
        conn, schema, df, meta = load_demo()
    except Exception as exc:  # pragma: no cover - demo missing is a build error
        st.error(f"Could not load demo dataset: {exc}")
        return False

    ss = st.session_state
    if ss.get("conn") is not None:
        try:
            ss.conn.close()
        except Exception:
            pass
    ss.conn = conn
    ss.schema = schema
    ss.tables = {}
    ss.dataset_name = DEMO_NAME
    ss.dataset_meta = meta
    ss.dataset_df = df
    state.reset_query()
    return True


# ---------------------------------------------------------------------------
# LLM call result type
# ---------------------------------------------------------------------------


@dataclass
class _LlmCallResult:
    """Outcome of a single ``nl_to_query_model`` call."""

    status: str  # "accepted" | "rejected" | "error" | "python_route"
    model: Optional[QueryModel]
    latency_ms: float
    detail: str = ""  # extra info: retry succeeded, error message, etc.


def _call_llm(nl: str, schema: dict, cfg: LLMConfig) -> _LlmCallResult:
    """Call the configured LLM and return a structured result.

    Never raises — every failure mode is encoded in the returned
    ``_LlmCallResult.status``.
    """
    try:
        client = make_llm_client(cfg)
    except Exception as exc:  # pragma: no cover - construction is pure
        return _LlmCallResult(
            status="error",
            model=None,
            latency_ms=0.0,
            detail=f"could not construct LLM client: {exc}",
        )

    t0 = time.perf_counter()
    try:
        model = nl_to_query_model(nl, schema, client=client, config=cfg)
    except RouteToPythonError as exc:
        return _LlmCallResult(
            status="python_route",
            model=None,
            latency_ms=(time.perf_counter() - t0) * 1000.0,
            detail=str(exc),
        )
    except LLMError as exc:
        return _LlmCallResult(
            status="error",
            model=None,
            latency_ms=(time.perf_counter() - t0) * 1000.0,
            detail=str(exc),
        )
    except Exception as exc:  # pragma: no cover - defensive
        return _LlmCallResult(
            status="error",
            model=None,
            latency_ms=(time.perf_counter() - t0) * 1000.0,
            detail=f"unexpected error: {exc}",
        )

    return _LlmCallResult(
        status="accepted",
        model=model,
        latency_ms=(time.perf_counter() - t0) * 1000.0,
    )


# ---------------------------------------------------------------------------
# Heuristic column
# ---------------------------------------------------------------------------


def _render_heuristic_column(result: HeuristicResult) -> None:
    """Render the offline heuristic's plan, or an 'unrecognized' state."""
    st.markdown("##### ⚙ Heuristic (offline, regex + token rules)")
    st.caption("Runs locally — no model call, no network.")

    if not result.parsed:
        st.error("✗ Unrecognized — out of the heuristic's scope.")
        if result.reasoning:
            with st.expander("Why", expanded=False):
                for r in result.reasoning:
                    st.markdown(f"- {r}")
        st.markdown(
            "<p style='color:#8E867B;font-size:12px;'>"
            "The heuristic only covers a small subset of analytics phrasing "
            "(see <code>src/heuristic_nl.py</code>). Anything outside that "
            "scope is intentionally refused rather than guessed."
            "</p>",
            unsafe_allow_html=True,
        )
        return

    st.success(f"✓ Parsed  ·  confidence **{result.confidence:.2f}**")
    st.progress(min(1.0, max(0.0, result.confidence)))

    if result.reasoning:
        with st.expander("Reasoning", expanded=True):
            for r in result.reasoning:
                st.markdown(f"- {r}")

    if result.unrecognized:
        with st.expander(f"Unrecognized tokens ({len(result.unrecognized)})", expanded=False):
            st.write(result.unrecognized)

    sql = result.model.to_sql()
    st.markdown("**Generated SQL**")
    st.code(sql, language="sql")


# ---------------------------------------------------------------------------
# LLM column
# ---------------------------------------------------------------------------


_STATUS_BADGES = {
    "accepted": ("✓ accepted", "#3F8A4F", "#E1F0E2", "#C8DDC9"),
    "rejected": ("✗ rejected", "#8A4A11", "#FAE7D0", "#E9C79A"),
    "error":    ("✗ LLM error", "#8A4A11", "#FAE7D0", "#E9C79A"),
    "python_route": ("↪ routed to Python analytics", "#1D4ED8", "#E0E7F4", "#C7D2E8"),
}


def _render_llm_column(
    call: Optional[_LlmCallResult],
    cfg: LLMConfig,
) -> None:
    """Render the LLM's plan, an idle placeholder, or an error state."""
    provider_label = {
        "ollama": "Ollama",
        "ollama_remote": "Remote Ollama",
        "groq": "Groq",
        "gemini": "Gemini",
    }.get(cfg.provider, cfg.provider)
    st.markdown(
        f"##### 🧠 LLM ({provider_label} · `{cfg.model}`)"
    )
    st.caption("Calls the configured model only when you press *Run comparison*.")

    if call is None:
        st.info("Press **Run comparison** below to call the model.")
        return

    badge_text, fg, bg, border = _STATUS_BADGES.get(
        call.status, _STATUS_BADGES["error"]
    )
    st.markdown(
        f'<span style="display:inline-flex;align-items:center;gap:6px;'
        f'padding:2px 10px;border-radius:999px;font-size:12px;'
        f"color:{fg};background:{bg};border:1px solid {border};\">"
        f"{badge_text}"
        f"<span style='margin-left:6px;opacity:0.7;'>"
        f"{call.latency_ms:.0f} ms</span>"
        f"</span>",
        unsafe_allow_html=True,
    )

    if call.status == "error":
        st.error(call.detail or "The LLM call failed.")
        st.caption(
            "The error is caught here — nothing was sent to the database. "
            "Fix the connection or pick a different model in ⚙ LLM."
        )
        return

    if call.status == "python_route":
        st.warning("Routed away from SQL — the heuristic should be your next stop.")
        st.markdown(call.detail)
        st.caption(
            "The LLM recognized an intent the SQL engine can't express "
            "(percentile, rolling window, etc.). The Python analytics path "
            "in the Studio handles it; this page only shows SQL plans."
        )
        return

    # status == "accepted"
    model = call.model
    if model is None:  # defensive — should not happen on "accepted"
        st.error("LLM returned an empty plan.")
        return

    with st.expander("Query plan (JSON)", expanded=False):
        st.json(_model_to_dict(model))

    sql = model.to_sql()
    st.markdown("**Generated SQL**")
    st.code(sql, language="sql")


def _model_to_dict(model: QueryModel) -> dict:
    """Best-effort serialisation of a ``QueryModel`` for the JSON viewer."""
    try:
        from dataclasses import asdict
        return asdict(model)
    except Exception:
        return {"repr": repr(model)}


# ---------------------------------------------------------------------------
# Handoff: write the chosen plan into session state and switch page
# ---------------------------------------------------------------------------


def _handoff(model: QueryModel) -> None:
    """Copy ``model`` into the Studio's session state and navigate there."""
    ss = st.session_state
    ss.model = copy.deepcopy(model)
    try:
        ss.last_sql = model.to_sql()
    except Exception as exc:
        st.error(f"Could not render SQL for the chosen plan: {exc}")
        return
    # The Studio's state.init() defaults ``model`` to an empty QueryModel.
    # Our deep-copied plan replaces that.
    st.switch_page("src/streamlit_app/pages/studio.py")


# ---------------------------------------------------------------------------
# Page entry point
# ---------------------------------------------------------------------------


def render() -> None:
    st.set_page_config(
        page_title="Query Studio · LLM SQL Assistant",
        page_icon="🧠",
        layout="wide",
        initial_sidebar_state="expanded",
    )
    inject_css()
    state.init()
    _render_safety_banner()

    st.markdown(
        "<h2 style='margin:8px 0 4px 0;'>LLM SQL Assistant</h2>"
        "<p style='color:#57514A;font-size:13px;margin:0 0 18px 0;'>"
        "Ask in plain English — see what the offline heuristic parses "
        "instantly, then run the same question through the LLM and "
        "compare the two query plans. Neither path executes SQL on this page."
        "</p>",
        unsafe_allow_html=True,
    )

    if not _ensure_schema_loaded():
        st.stop()

    schema: dict = st.session_state.schema
    cfg: LLMConfig = load_llm_config(load_config() or {})

    # ---- Input row ------------------------------------------------------
    # Chip clicks set ``_chip_prefill``; we apply it to the text-area
    # session_state key BEFORE the widget is instantiated, otherwise
    # Streamlit raises (you can't mutate a widget key after creation).
    prefill = st.session_state.pop("_llm_showcase_chip_prefill", None)
    if prefill is not None:
        st.session_state["llm_showcase_nl"] = prefill

    nl = st.text_area(
        "Ask in plain English",
        key="llm_showcase_nl",
        placeholder=(
            "e.g. monthly revenue trend 2024, "
            "top 10 customers by margin, "
            "or compare EMEA vs AMER year-over-year"
        ),
        height=80,
    )

    # Example chips — they only set a prefill key (read on the next run).
    chip_cols = st.columns(len(_EXAMPLE_QUESTIONS))
    for col, example in zip(chip_cols, _EXAMPLE_QUESTIONS):
        with col:
            if st.button(example, key=f"chip_{example}", width="stretch"):
                st.session_state["_llm_showcase_chip_prefill"] = example
                st.rerun()

    run_clicked = st.button(
        "▶ Run comparison",
        type="primary",
        width="stretch",
        disabled=not nl.strip(),
        key="llm_showcase_run",
    )

    st.caption(
        f"Schema: **{st.session_state.get('dataset_name', '—')}** · "
        f"{len(schema)} columns. The heuristic reruns on every change; "
        f"the LLM only runs when you press *Run comparison*."
    )

    # ---- Heuristic (eager, free) ----------------------------------------
    heuristic: HeuristicResult = parse_heuristic(nl, schema)

    # ---- LLM (on demand) ------------------------------------------------
    llm_call: Optional[_LlmCallResult] = None
    if run_clicked and nl.strip():
        with st.spinner(f"Calling {cfg.provider} · {cfg.model}…"):
            llm_call = _call_llm(nl, schema, cfg)

    # ---- Two-column comparison ------------------------------------------
    col_h, col_l = st.columns(2, gap="large")
    with col_h:
        with st.container(border=True, key="llm_heuristic_panel"):
            _render_heuristic_column(heuristic)
    with col_l:
        with st.container(border=True, key="llm_assistant_panel"):
            _render_llm_column(llm_call, cfg)

    # ---- Handoff buttons -----------------------------------------------
    st.markdown("---")
    st.markdown("**Use one of the plans above in the Studio**")
    st.caption(
        "Picks the chosen ``QueryModel`` and switches back to the Studio, "
        "where the SQL preview will already be filled in. Nothing runs "
        "until you press **▶ Run query** there."
    )

    btn_cols = st.columns([1, 1, 1, 3])
    with btn_cols[0]:
        use_h = st.button(
            "Use heuristic plan",
            width="stretch",
            disabled=not heuristic.parsed,
            key="llm_handoff_heuristic",
        )
    with btn_cols[1]:
        use_l = st.button(
            "Use LLM plan",
            width="stretch",
            disabled=not (llm_call and llm_call.model is not None),
            key="llm_handoff_llm",
        )

    if use_h and heuristic.parsed and heuristic.model is not None:
        _handoff(heuristic.model)
    if use_l and llm_call and llm_call.model is not None:
        _handoff(llm_call.model)
